# Generated by Django 5.0.1 on 2024-01-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0002_administrators_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
