# Generated by Django 5.0.1 on 2024-01-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0003_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
    ]
