# Generated by Django 5.0.1 on 2024-01-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0004_alter_customers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
