# Generated by Django 5.0.1 on 2024-01-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0005_customers_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
