# Generated by Django 5.0.1 on 2024-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0007_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='persons_rated',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pimage',
            field=models.ImageField(blank=True, db_column='PImage', max_length=200, null=True, upload_to='product_image'),
        ),
    ]
