# Generated by Django 5.0.1 on 2024-01-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0008_products_persons_rated_products_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
    ]
