# Generated by Django 5.0.1 on 2024-01-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0009_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
