# Generated by Django 5.0.1 on 2024-01-17 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0011_alter_cartcontainers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartcontainers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'managed': False},
        ),
    ]
