# Generated by Django 5.0.1 on 2024-01-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0012_alter_cartcontainers_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'managed': True},
        ),
    ]
