# Generated by Django 5.0.1 on 2024-01-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0014_alter_shoppingcarts_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartcontainers',
            options={'managed': True},
        ),
    ]
