# Generated by Django 5.0.1 on 2024-01-17 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0016_alter_cartcontainers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
