# Generated by Django 5.0.1 on 2024-01-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0017_alter_products_options_shoppingcarts_custid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcarts',
            options={'managed': False},
        ),
    ]
