# Generated by Django 5.0.1 on 2024-01-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0017_alter_shoppingcarts_options'),
        ('ShopEzy_App', '0018_alter_shoppingcarts_options'),
    ]

    operations = [
    ]
