# Generated by Django 5.0.1 on 2024-01-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0019_merge_20240118_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
    ]
