# Generated by Django 5.0.1 on 2024-01-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0020_alter_customers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
