# Generated by Django 5.0.1 on 2024-01-18 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0021_customers_is_active_customers_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': False},
        ),
    ]
