# Generated by Django 5.0.1 on 2024-01-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0022_alter_customers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
    ]
