# Generated by Django 5.0.1 on 2024-01-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEzy_App', '0023_alter_customers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='is_staff',
        ),
    ]
